  GNU nano 8.7                                                                                    docker-compose.yml
# Servidor Backend PHP (Apache)
  app:
    image: php:8.2-apache
    container_name: proviemplea_backend
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    # Añadimos esta línea para que Apache reconozca el .htaccess y active el mod_rewrite
    command: >
      sh -c "a2enmod rewrite && apache2-foreground"




















